version: "3.9"

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    restart: always

  root-frontend:
    build: ./root-frontend
    container_name: root-frontend
    environment:
      - VIRTUAL_HOST=skravops.xyz
      - LETSENCRYPT_HOST=skravops.xyz
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}


  devops-frontend:
    build: ./devops-frontend
    container_name: devops-frontend
    environment:
      - VIRTUAL_HOST=devops.skravops.xyz
      - LETSENCRYPT_HOST=devops.skravops.xyz
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "80"

  secops-frontend:
    build: ./secops-frontend
    container_name: secops-frontend
    environment:
      - VIRTUAL_HOST=secops.skravops.xyz
      - LETSENCRYPT_HOST=secops.skravops.xyz
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "80"

  music-frontend:
    build: ./music-frontend
    container_name: music-frontend
    environment:
      - VIRTUAL_HOST=music.skravops.xyz
      - LETSENCRYPT_HOST=music.skravops.xyz
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "80"


  music-api:
    build: ./music-api
    container_name: music-api
    environment:
      - VIRTUAL_HOST=api.music.skravops.xyz
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=api.music.skravops.xyz
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - ./mongo-data:/data/db

