version: "3.9"

services:

  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - devops-frontend
      - secops-frontend
      - music-frontend
      - music-api

  devops-frontend:
    build: ./devops-frontend
    container_name: devops-frontend

  secops-frontend:
    build: ./secops-frontend
    container_name: secops-frontend

  music-frontend:
    build: ./music-frontend
    container_name: music-frontend

  music-api:
    build: ./music-api
    container_name: music-api
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - ./mongo-data:/data/db

